[project]
name = "anytime-py-benchmark"
version = "1.0.0"
description = "Hi!"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = []

[dependency-groups]
dev = [
    "pytest-codspeed>=4.2.0",
]
